project .net/Controllers/ProfileController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using project_.net.Database;
using project_.net.Models;

namespace project_.net.Controllers
{
    public class ProfileController : Controller
    {
        ClientRepository rep1 = new ClientRepository();
        public IActionResult ProfileDetails( String success)
        {
            ViewBag.success = success;
            if (HttpContext.Session.GetInt32("user") != 1)
            {
                return RedirectToAction("Signin","Home");
            }
            else
            {
                ViewData["NavMenuPage"] = "connected";
                Client c = rep1.getClientById(HttpContext.Session.GetInt32("userId")??-1);
                return View(c);
            }
        
    }
        ReservationRepository rep2 = new ReservationRepository();
        public IActionResult History(String success)
        {
            ViewBag.success = success;
        if (HttpContext.Session.GetInt32("user")!=1)
            {
                return RedirectToAction("Signin","Home");
            }
            else
            {            ViewData["NavMenuPage"] = "connected";

            var r = rep2.getReservationsByClientId(HttpContext.Session.GetInt32("userId") ?? -1);
            return View(r);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, IFormCollection collection)
        {
            Client c = rep1.getClientById(id);
            c.Name = collection["Name"];
            c.email = collection["email"];
            c.password = collection["password"];
            c.phoneNumber = collection["phone"];
            rep1.editClient(c);
            return RedirectToAction(nameof(ProfileDetails),new {success = "Profile Changed Successfully"});
        }

        public ActionResult DeleteReservation(int id)
        {
            if (HttpContext.Session.GetInt32("user") != 1)
            {
                return RedirectToAction("Signin", "Home");
            }
            else
            {
                rep2.deleteReservation(id);
                return RedirectToAction(nameof(History),new {success =$"Reservation {id} is Deleted Successfully"});
            }
        }
    }
}

project .net/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using project_.net.Database;
using project_.net.Models;

namespace project_.net.Controllers

{
   
    public class RestaurantController : Controller
    {
        public List<Category> category = new List<Category>(){ new Category("americaine") , new Category("Française") , new Category("Tunisienne") , new Category("italienne") , new Category("lobneniya") };


        public List<Restaurant> RestaurantData = new List<Restaurant>()
        {
            new Restaurant("PastaCosi","Lac","https://media-cdn.tripadvisor.com/media/photo-s/15/5c/32/63/pasta-fruits-de-mer.jpg" , 40),
            new Restaurant("twoM","hammamet","https://media.cntraveler.com/photos/5b22bfdf633da74cbe8bd873/master/w_1200,c_limit/Buca-Yorkville_Rick-O'Brien_2018_BUCA_4SEASONS_092-(8).jpg?mbid=social_retweet",20),
                new Restaurant("baristas","centre urbain nord" ,"https://th.bing.com/th/id/OIP.4Q39EptrW14YfZZ-8vc8mgHaFj?pid=ImgDet&rs=1",40),
                    new Restaurant("khalil","tunis","https://th.bing.com/th/id/R.0a5ff9269f7d485895700daa46b8216c?rik=ks0%2bPBqoLDTWIQ&pid=ImgRaw&r=0",22),
                        new Restaurant("pizza","sokra","https://th.bing.com/th/id/OIP.mudFr3EWGVKiUCzJttcErQHaEi?pid=ImgDet&rs=1",19),
                            new Restaurant("burger","aouina","https://img.tagvenue.com/resize/6f/c6/widen-1680-noupsize;2944-the-restaurant-room.jpg",45),
                            new Restaurant("lasagne","ariana","https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/935c1071711569.5bcee78e4e619.jpg",18),
                            new Restaurant("hiii","nabeul","https://i.pinimg.com/originals/51/61/a9/5161a9904eea6222ec3fdc2f0528504b.jpg",40)

        };

        RestaurantRepository repository = new RestaurantRepository();
        ReservationRepository reservationRepository = new ReservationRepository();
        public IActionResult Index(String success)
        {
            ViewBag.success = success;
            if (HttpContext.Session.GetInt32("user") != 1)
            {
                return RedirectToAction("Signin", "Home");
            }
            else
            {
                ViewData["NavMenuPage"] = "connected";
                var restaurants = repository.getRestaurants();
                return View(restaurants);
            }
        }
        [HttpPost]
        public IActionResult RestaurantsByName(IFormCollection collection)
        {
            if (HttpContext.Session.GetInt32("user") != 1)
            {
                return RedirectToAction("Signin", "Home");
            }
            else
            {
                ViewData["NavMenuPage"] = "connected";
                ViewBag.search = collection["search"];
                var restaurants = repository.RestaurantListByName(collection["search"]);
                return View(restaurants);
            }
        }


        public IActionResult restaurant_detail(int id)
        {
            if (HttpContext.Session.GetInt32("user") != 1)
            {
                return RedirectToAction("Signin","Home");

            }
            else
            {
                ViewData["NavMenuPage"] = "connected";
                Restaurant restaurant = repository.getRestaurantById(id);
                return View(restaurant);

            }

        }
        public IActionResult add()
        {
            if (HttpContext.Session.GetInt32("user") == 1)
            {
                RestaurantRepository restaurantRepository = new RestaurantRepository();
                Restaurant restaurant = new Restaurant("hiuypo", "kdfsvb","lids",3); 
                restaurantRepository.addRestaurant(restaurant);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction("Signin","Home");
            }
        }

        public IActionResult Faker()
        {
            if (HttpContext.Session.GetInt32("user") == 1)
            {
                FakeDataGenerator.Restaurants();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return RedirectToAction("Signin","Home");
            }
        }
        [HttpGet]
        public IActionResult book(int id)
        {
            ViewData["NavMenuPage"] = "connected";
            ViewBag.id = id;
            return View(id);
        }
        [HttpPost]
        public IActionResult book(IFormCollection collection,int id)
        {
           
            reservationRepository.addReservation(HttpContext.Session.GetInt32("userId")??-1,id,DateTime.Parse(collection["Date"]),Int32.Parse(collection["Places"]));
            return RedirectToAction(nameof(Index),new {success=$"Reservation {id} is Created Successfully"});
        }
    }
}
/*
public IActionResult ListeRestaurant()
{
    var restaurants = getlist();

[HttpGet]
public IActionResult book()
{
    return View();
}

}

}
*/

project .net/Views/Shared/Components/NavMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

public class NavMenuViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync(string pageName)
    {
        var links = GetLinksForPage(pageName);
        return View(links);
    }

    private Dictionary<string, string> GetLinksForPage(string pageName)
    {
        Dictionary<string, string> links = null;
        switch (pageName)
        {
            case "default":
                links = new Dictionary<string, string> {
                };

                break;

            case "Admin":
                links = new Dictionary<string, string> {
                    { "search", "/admin/RestaurantsByName" },
                    { "signout", "/Admin/Signout" },
                };

                break;

            case "connected":
                links = new Dictionary<string, string> {
                    { "search", "/Restaurant/RestaurantsByName" },
                    { "profile", "../Profile/ProfileDetails" },
                    { "signout", "/Home/Signout" },
                };

                break;
            case "disconnected":
                links = new Dictionary<string, string> {
                 { "Sign in", "../Home/Signin" },
                 { "Sign up", "..Home/Signup" },
                };

                break;

        }


        return links;
    }
}

project .net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - project_.net</title>
    
    <link rel="stylesheet" href="https://bootswatch.com/5/spacelab/bootstrap.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
</head>
<body >
<header>
    @if (ViewData["NavMenuPage"] != null)
    {
        @await Component.InvokeAsync("NavMenu", ViewData["NavMenuPage"])
        <!-- <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="https://i.pinimg.com/564x/2a/c5/60/2ac560c628f1577e6db6ade2117ce828.jpg" style="width:50px" />
                <a class="navbar-brand" asp-area="" asp-controller="Restaurant" asp-action="index" style="text-decoration:none;color:black">MyRestaurant.net</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="book">book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="ProfileDetails">Details</a>
                        </li>
                    </ul>
                </div>
                <form class="d-flex" action="/Restaurant/RestaurantsByName" method="post">
                    <input class="form-control me-sm-2" name="search" type="search" placeholder="Search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>-->
    }
</header>
<div style="padding-top:100px" class="container">
    
@if (ViewBag.error!=null && ViewBag.error != "")
{<div class="alert alert-danger" role="alert">@ViewBag.error</div>}
@if (ViewBag.success!=null && ViewBag.success != "")
{<div class="alert alert-success" role="alert">@ViewBag.success</div>}

    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
<section class="align-baseline">
  <!-- Footer -->
    <footer class="bg-dark text-white text-center font-weight-light" style="font-size:14px">
    <!-- Grid container -->
    <div class="container ">
      <!--Grid row-->
            <div class="row py-3">

        <!--Grid column-->
        <div class="col-6 col-md-4 ">
                    <p class="text-white font-weight-bold" style="font-size:16px">Let's do it together</p>
         <ul class="list-unstyled mb-0">
            <li>
                            <a href="#!" class="text-white" style="text-decoration:none">Partners</a>
            </li>
            <li>
                            <a href="#!" class="text-white" style="text-decoration:none">Contact us</a>
            </li>
             
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-6 col-md-4 ">
                    <p class="text-white font-weight-bold " style="font-size:16px">Links of interest</p>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="#!" class="text-white" style="text-decoration:none ">About us</a>
            </li>
            <li>
              <a href="#!" class="text-white" style="text-decoration:none">FAQ</a>
            </li>
            <li>
              <a href="#!" class="text-white" style="text-decoration:none">Terms & Conditions</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
                <div class="col-6 col-md-4">
                    <p class="text-white font-weight-bold" style="font-size:16px">Follow us</p>

          <ul class="list-unstyled">
            <li>
               <a href="#!" class="text-white" style="text-decoration:none">Facebook</a>
            </li>
            <li>
                 <a href="#!" class="text-white" style="text-decoration:none" >Twitter</a>
            </li>
            <li>
               <a href="#!" class="text-white" style="text-decoration:none">Instagram</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
        <div class="text-center p-3 font-weight-light" style="background-color:#1A1A1A;">
      © 2023 Copyright
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</section>
</html>